version: "3.8"
services:
  conventions-site:
    container_name: conventions-site
    image: gordonpn/conventions-guide
    expose:
      - "80"
    restart: always
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: curl --fail -s http://localhost:80/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - web
    labels:
      - "traefik.enable=true"

networks:
  web:
    external: true
